# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration

require:
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*.rb'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'config/environments/**/*'
    - 'config/initializers/devise.rb'
    - 'spec/**/*'
    - 'test/**/*'
    - 'lib/tasks/**/*'
    - 'config/initializers/*'
    - 'config/boot.rb'
    - 'config/puma.rb'
    - 'config/spring.rb'
    - 'config/application.rb'
    - 'config/environment.rb'
    - 'config/routes.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 150

Metrics/AbcSize:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 8

Layout/LineLength:
  Max: 100

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '()'
    '%i': '[]'
    '%I': '[]'

Rails/HttpPositionalArguments:
  Enabled: false

# Custom inclusions and exclusions for specific cops
Layout/IndentationWidth:
  Width: 2

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Rails-specific configurations
Rails/SaveBang:
  Exclude:
    - 'db/migrate/*'

Rails/OutputSafety:
  Enabled: true

# Enable specific cops for security
Security/YAMLLoad:
  Enabled: true

Security/Eval:
  Enabled: true

Security/JSONLoad:
  Enabled: true